const students = [
  {
    id: 1,
    firstName: "John Doe",
    lastName: "John Doe",
    email: "johndoe@example.com",
    phone: "123-456-7890",
  },
  {
    id: 2,
    firstName: "Jane Smith",
    lastName: "Jane Smith",
    email: "janesmith@example.com",
    phone: "234-567-8901",
  },
  {
    id: 3,
    firstName: "Emily Johnson",
    lastName: "Emily Johnson",
    email: "emilyjohnson@example.com",
    phone: "345-678-9012",
  },
  {
    id: 4,
    firstName: "Michael Brown",
    lastName: "Michael Brown",
    email: "michaelbrown@example.com",
    phone: "456-789-0123",
  },
  {
    id: 5,
    firstName: "Jessica Davis",
    lastName: "Jessica Davis",
    email: "jessicadavis@example.com",
    phone: "567-890-1234",
  },
  {
    id: 6,
    firstName: "David Wilson",
    lastName: "David Wilson",
    email: "davidwilson@example.com",
    phone: "678-901-2345",
  },
  {
    id: 7,
    firstName: "Sophia Martinez",
    lastName: "Sophia Martinez",
    email: "sophiamartinez@example.com",
    phone: "789-012-3456",
  },
  {
    id: 8,
    firstName: "Daniel Anderson",
    lastName: "Daniel Anderson",
    email: "danielanderson@example.com",
    phone: "890-123-4567",
  },
  {
    id: 9,
    firstName: "Olivia Thomas",
    lastName: "Olivia Thomas",
    email: "oliviathomas@example.com",
    phone: "901-234-5678",
  },
  {
    id: 10,
    firstName: "Matthew Taylor",
    lastName: "Matthew Taylor",
    email: "matthewtaylor@example.com",
    phone: "012-345-6789",
  },
  {
    id: 11,
    firstName: "Ava Hernandez",
    lastName: "Ava Hernandez",
    email: "avahernandez@example.com",
    phone: "123-456-7890",
  },
  {
    id: 12,
    firstName: "Elijah Moore",
    lastName: "Elijah Moore",
    email: "elijahmoore@example.com",
    phone: "234-567-8901",
  },
  {
    id: 13,
    firstName: "Isabella White",
    lastName: "Isabella White",
    email: "isabellawhite@example.com",
    phone: "345-678-9012",
  },
  {
    id: 14,
    firstName: "James Garcia",
    lastName: "James Garcia",
    email: "jamesgarcia@example.com",
    phone: "456-789-0123",
  },
  {
    id: 15,
    firstName: "Mia Rodriguez",
    lastName: "Mia Rodriguez",
    email: "miarodriguez@example.com",
    phone: "567-890-1234",
  },
  {
    id: 16,
    firstName: "Benjamin Lee",
    lastName: "Benjamin Lee",
    email: "benjaminlee@example.com",
    phone: "678-901-2345",
  },
  {
    id: 17,
    firstName: "Charlotte Walker",
    lastName: "Charlotte Walker",
    email: "charlottewalker@example.com",
    phone: "789-012-3456",
  },
  {
    id: 18,
    firstName: "Lucas Hall",
    lastName: "Lucas Hall",
    email: "lucashall@example.com",
    phone: "890-123-4567",
  },
  {
    id: 19,
    firstName: "Amelia Allen",
    lastName: "Amelia Allen",
    email: "ameliaallen@example.com",
    phone: "901-234-5678",
  },
  {
    id: 20,
    firstName: "Alexander Young",
    lastName: "Alexander Young",
    email: "alexanderyoung@example.com",
    phone: "012-345-6789",
  },
];

module.exports = students;
