export const mockMcqQuestions = [
  {
    QuestionID: 3006,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Berlin",
    OptionB: "b) Madrid",
    OptionC: "c) Paris",
    OptionD: "d) Rome",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3007,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Earth",
    OptionB: "b) Mars",
    OptionC: "c) Jupiter",
    OptionD: "d) Venus",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3008,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Harper Lee",
    OptionB: "b) J.K. Rowling",
    OptionC: "c) George Orwell",
    OptionD: "d) Jane Austen",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3009,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) H2O",
    OptionB: "b) CO2",
    OptionC: "c) O2",
    OptionD: "d) H2",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3010,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Atlantic Ocean",
    OptionB: "b) Indian Ocean",
    OptionC: "c) Pacific Ocean",
    OptionD: "d) Arctic Ocean",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3011,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Helium",
    OptionB: "b) Hydrogen",
    OptionC: "c) Oxygen",
    OptionD: "d) Carbon",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3012,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Saturn",
    OptionB: "b) Jupiter",
    OptionC: "c) Neptune",
    OptionD: "d) Uranus",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3013,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Leonardo da Vinci",
    OptionB: "b) Michelangelo",
    OptionC: "c) Raphael",
    OptionD: "d) Vincent van Gogh",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3014,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Gold",
    OptionB: "b) Diamond",
    OptionC: "c) Iron",
    OptionD: "d) Graphite",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3015,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Gold",
    OptionB: "b) Diamond",
    OptionC: "c) Iron",
    OptionD: "d) Graphite",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3016,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) Gold",
    OptionB: "b) Diamond",
    OptionC: "c) Iron",
    OptionD: "d) Graphite",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
  {
    QuestionID: 3017,
    QuestionType: "MCQ",
    QuestionDescription:
      "This is a test description for placeholder perpurses tasjdf;lkasjd;flkjasd;lfkja;lsdkjflkasdmckmewpiohtrq[owehfkmnq[woekhf[oqwejr]]] \n int main() {\n     printf('hi'); \n     return 0; \n }",
    OptionA: "a) 1910",
    OptionB: "b) 1912",
    OptionC: "c) 1914",
    OptionD: "d) 1916",
    OptionE: null,
    OptionF: null,
    IsActive: true,
    Timing: null,
    Answer: "",
    Status: "Not Attempted",
  },
];
